# .pre-commit-config.yaml

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # 使用一个较新的、稳定的版本
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=10240'] # 检查是否有超过10MB的大文件被添加

-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python3.9 # 指定你的Python版本